### ISSUE TITLE
Inside intSiteValidationOUTPUT.tar.gz, HIV_CTRL samples, multihits don't have ID column

### ISSUE THREAD

**Issue by yhwu** [esherm/BushmanIntSites#14]
other samples have ID

> multihits
> GRanges object with 2 ranges and 2 metadata columns:
>     seqnames                 ranges strand |        revmap    counts
>        <Rle>              <IRanges>  <Rle> | <IntegerList> <integer>
>   1     chr8 [145364386, 145364440]      - |             1         1
>   2     chr8 [145432259, 145432313]      - |             2         1
> ---
> 
>   seqinfo: 25 sequences from hg18 genome

**Comment by esherm** [comment]
multihitData[[2]] is the dereplicated multihits object and shouldn't have an ID value.  The actual ID values are contained in multihitData[[1]].

Other samples that didn't have any multihits show an ID column for multihitData[[_2_]] because the dereplication process was aborted due to having nothing to dereplicate.

Fixing this now.

**Comment by esherm** [comment]
resolved with 13d8659353275cbe04746cd12968118b72604ac1

Code should now be ready to run on PMACS
